#todo, refaktorisati pozivanje`
basic_qts = {
    '1': { #Football
        'initial_odds': {
            'LTT1': 0,
            'MTT1': 0,
            'LT1': 0,
            'LTT2': 0,
            'MTT2': 0,
            'LT2': 0,
            'ZHT1': 0,
            'ZHTX': 0,
            'ZHT2': 0,
            'Z1': 0,
            'ZX': 0,
            'Z2': 0,
            'F1': 0,
            'FX': 0,
            'F2': 0,
            'DC1X': 0,
            'DC12': 0,
            'DCX2': 0,
            'Q1': 0,
            'Q2': 0,
            'FHT1': 0,
            'FHTX': 0,
            'FHT2': 0,
            'NG1': 0,
            'NGX': 0,
            'NG2': 0,
            'o1_1': 0,
            'o1_X': 0,
            'o1_2': 0,
            'X_1': 0,
            'X_X': 0,
            'X_2': 0,
            'o2_1': 0,
            'o2_X': 0,
            'o2_2': 0,
            'NCN1': 0,
            'NCNX': 0,
            'NCN2': 0,
            'LST_CN1': 0,
            'LST_CN2': 0,
            'W1': 0,
            'W2': 0,
            'LSTS1': 0,
            'LSTSX': 0,
            'LSTS2': 0,
            'ODD': 0,
            'EVEN': 0,
            'M1_GG': 0,
            'M1_NG': 0,
            'M2_GG': 0,
            'M2_NG': 0,
            'MX_GG': 0,
            'MX_NG': 0,
            'GG': 0,
            'NG': 0,
            'GGht1': 0,
            'NGHT1': 0,
            'GGht2': 0,
            'NGGht2': 0,
            'GGHT': 0,
            'NGGht1': 0,
            'GGHT2': 0,
            'NGHT2': 0,
            'LFT': 0,
            'MTFT': 0,
            'LTFT': 0,
            'LHT': 0,
            'MTHT': 0,
            'LTHT': 0,
            '_1YCS': 0,
            '_1NCS': 0,
            '_2YCS': 0,
            '_2NCS': 0,
            'SHT1': 0,
            'SHTX': 0,
            'SHT2': 0,
            'NGHT1Y': 0,
            'NGHT1N': 0,
            'NGHT2Y': 0,
            'NGHT2N': 0,
            'NGST1Y': 0,
            'NGST1N': 0,
            'NGST2Y': 0,
            'NGST2N': 0,
            'T1W90': 0,
            'T2W90': 0,
            'T1WET': 0,
            'T2WET': 0,
            'T1WP': 0,
            'T2WP': 0,
            'YET': 0,
            'NET': 0,
            'HTCS_1-0': 0,
            'HTCS_0-0': 0,
            'HTCS_0-1': 0,
            'HTCS_1-1': 0,
            'HTCS_2-1': 0,
            'HTCS_1-2': 0,
            'HTCS_2-2': 0,
            'HTCS_3-2': 0,
            'HTCS_2-3': 0,
            'HTCS_3-3': 0,
            'HTCS_4-3': 0,
            'HTCS_3-4': 0,
            'HTCS_4-4': 0,
            'HTCS_5-4': 0,
            'HTCS_4-5': 0,
            'HTCS_5-5': 0,
            'HTCS_6-5': 0,
            'HTCS_5-6': 0,
            'HTCS_6-6': 0,
            'HTCS_7-6': 0,
            'HTCS_6-7': 0,
            'HTCS_7-7': 0,
            'HTCS_8-7': 0,
            'HTCS_7-8': 0,
            'HTCS_8-8': 0,
            'HTCS_9-8': 0,
            'HTCS_8-9': 0,
            'HTCS_9-9': 0,
            'CS_0-1': 0,
            'CS_1-1': 0,
            'CS_2-1': 0,
            'CS_1-2': 0,
            'CS_2-2': 0,
            'CS_3-2': 0,
            'CS_2-3': 0,
            'CS_3-3': 0,
            'CS_4-3': 0,
            'CS_3-4': 0,
            'CS_4-4': 0,
            'CS_5-4': 0,
            'CS_4-5': 0,
            'CS_5-5': 0,
            'CS_6-5': 0,
            'CS_5-6': 0,
            'CS_6-6': 0,
            'CS_7-6': 0,
            'CS_6-7': 0,
            'CS_7-7': 0,
            'CS_8-7': 0,
            'CS_7-8': 0,
            'CS_8-8': 0,
            'CS_9-8': 0,
            'CS_8-9': 0,
            'CS_9-9': 0,
            'EXG1_0': 0,
            'EXG1_1': 0,
            'EXG1_2': 0,
            'EXG1_3p': 0,
            'EXG2A': 0,
            'EXG2B': 0,
            'EXG2C': 0,
            'EXG2D': 0,
            'ACNA': 0,
            '_2WCN_FTC': 0,
            'ACNHT_GTC': 0,
            'EXG2_3p': 0,
            'EXG2_2': 0,
            '3WH2': 0,
            'HB1': 0,
            '_2WCN_FT': 0,
            'LFTD': 0,
            'LHTA': 0,
            'LTHTC': 0,
            'T2_LTFTD': 0,
            'HD2': 0,
            'HAX': 0,
            'ACN_GTA': 0,
            'CN_EXD': 0,
            '3WH_1HT2C': 0,
            'LHTB': 0,
            '3WH': 0,
            'T1_MTFTC': 0,
            'CNC': 0,
            'EXCN_HTD': 0,
            'T2_LFTC': 0,
            'T2_LTFTB': 0,
            'LTFTC': 0,
            'CN_LTHTA': 0,
            'T1_LTFTA': 0,
            'ACS': 0,
            '3WHXC': 0,
            'CN_GT': 0,
            'T2_MTFTC': 0,
            'ACNHT_LTA': 0,
            'HTHD': 0,
            'HTHB': 0,
            'MTHTB': 0,
            '3WH_1HTX': 0,
            '3WHXA': 0,
            'ACSHT_A': 0,
            'CND': 0,
            'ACN_GT': 0,
            '_2WCN_LTFTC': 0,
            'CN_EXA': 0,
            '3WH1C': 0,
            'LHTD': 0,
            '3WH_1HT2B': 0,
            'HB': 0,
            'ACNB': 0,
            '_2WCN_MTFT': 0,
            'AH_HT2B': 0,
            'EXG2_9': 0,
            'CN_LTC': 0,
            '_2WCN_LTFTD': 0,
            '2WCN_LTFTC': 0,
            'T2_LFT': 0,
            'MTFTC': 0,
            '_2WCN_FTA': 0,
            'AH1C': 0,
            '3WH_1HT2': 0,
            'HDX': 0,
            'CN_LTHTD': 0,
            'AH': 0,
            'HTHDX': 0,
            'ACN': 0,
            'CN_MTHTB': 0,
            '_2WCN_LTFTA': 0,
            'AH1A': 0,
            'T1_LTFT': 0,
            'AH_HT1C': 0,
            'T2_MTFT': 0,
            'ACN_GTD': 0,
            'HA2': 0,
            '_2WCN_MTFTD': 0,
            'LTFTB': 0,
            '3WH_1HTXB': 0,
            'ACN_LTB': 0,
            'ACSHT_B': 0,
            'CN_MTHTD': 0,
            '3WHC': 0,
            'HTHA2': 0,
            'EXCN_HTC': 0,
            'CN': 0,
            'AH_HT2C': 0,
            'EXG1_9': 0,
            'CN_LTA': 0,
            '_2WCN_LTFT': 0,
            '3WH_1HT1': 0,
            'CN_HTD': 0,
            '3WH_1HTD': 0,
            'T2_LFTB': 0,
            'LTHTB': 0,
            'H2': 0,
            'EXG2_0': 0,
            'T1_LTFTC': 0,
            '3WHXB': 0,
            'CNA': 0,
            'CN_LTD': 0,
            'HD1': 0,
            'MTHTD': 0,
            'T1_LFTA': 0,
            'ACN_LTA': 0,
            '3WH_1HTA': 0,
            'EXG1_7': 0,
            'EXG1_3': 0,
            'AH_HT2': 0,
            'EXG2_5': 0,
            'T2_MTFTB': 0,
            'ACNHT_LTD': 0,
            '3WH_1HTXC': 0,
            'ACSHT_C': 0,
            'CN_LTHTC': 0,
            'HBX': 0,
            'AH_HTC': 0,
            'HTHD2': 0,
            '3WH1D': 0,
            'T1_LFTC': 0,
            'T2_LFTD': 0,
            'ACSD': 0,
            '3WH1B': 0,
            'T2_MTFTD': 0,
            'HTHBX': 0,
            'HTH': 0,
            'ACNHT_GTD': 0,
            'T1_MTFTB': 0,
            'ACNC': 0,
            'AH_HT2A': 0,
            'T1_LFTD': 0,
            'AH_HTD': 0,
            '_2WCN_FTB': 0,
            'EXG2_6': 0,
            'EXCN_HTA': 0,
            'ACNHT': 0,
            '3WH_1HT2D': 0,
            'T2_LTFT': 0,
            'ACNHT_GTA': 0,
            'ACSB': 0,
            'AH_HTA': 0,
            '3WHB': 0,
            'AHD': 0,
            'H': 0,
            '3WH2D': 0,
            'AH1': 0,
            '3WH_1HT1A': 0,
            'HTHD1': 0,
            'ACNHTA': 0,
            'HTHB1': 0,
            'LFTB': 0,
            'CN_HT': 0,
            'LFT_T1B': 0,
            'H1': 0,
            'EXG1_5': 0,
            '2WCN_MTFT': 0,
            '3WH_1HTXA': 0,
            'LTFTA': 0,
            'HC': 0,
            'HTHC1': 0,
            'LFT_T1': 0,
            'ACSHT_': 0,
            'EXG1_4': 0,
            'AH2C': 0,
            'ACNHT_LTC': 0,
            'ACN_LT': 0,
            'CN_MTHT': 0,
            'AH_HT1A': 0,
            'MTFTA': 0,
            '2WCN_MTFTA': 0,
            'ACNHT_LT': 0,
            'EXG1_6': 0,
            'AH_HT1': 0,
            'T1_LTFTB': 0,
            'ACNHTD': 0,
            'HTHC2': 0,
            '3WH_1HTB': 0,
            'ACNHT_GT': 0,
            '2WCN_MTFTD': 0,
            '3WH_1HT1B': 0,
            'HTHAX': 0,
            'EXG2_3': 0,
            'HTHA1': 0,
            '3WH_1HT': 0,
            'HA': 0,
            'CN_LTHTB': 0,
            '_2WCN_LTFTB': 0,
            '2WCN_MTFTB': 0,
            'HTHX': 0,
            'AHA': 0,
            'AH2D': 0,
            'CNB': 0,
            'CN_MTHTA': 0,
            '2WCN_LTFT': 0,
            'CN_GTA': 0,
            'ACN_LTC': 0,
            'AH_HT': 0,
            'CN_EXB': 0,
            'MTHTC': 0,
            '3WH1A': 0,
            'CN_LT': 0,
            'ACSHT_D': 0,
            'AH_HTB': 0,
            '3WH_1HTXD': 0,
            'CN_HTA': 0,
            '3WHD': 0,
            'HTH2': 0,
            'LTFTD': 0,
            'T2_LFTA': 0,
            'HD': 0,
            '3WH_1HT1D': 0,
            'CN_EX': 0,
            'MTHTA': 0,
            'EXG2_7': 0,
            '_2WCN_FTD': 0,
            'LFTC': 0,
            '3WH2A': 0,
            'AH2': 0,
            '3WHXD': 0,
            '3WH2B': 0,
            'HTH1': 0,
            '3WH_1HTC': 0,
            '3WH1': 0,
            'CN_HTC': 0,
            'EXG2_8': 0,
            'LHTC': 0,
            'CN_HTB': 0,
            'MTFTD': 0,
            'CN_GTD': 0,
            '3WH_1HT1C': 0,
            'T2_LTFTC': 0,
            'HB2': 0,
            'EXCN_HT': 0,
            '2WCN_LTFTB': 0,
            'T1_MTFT': 0,
            'T1_LTFTD': 0,
            '_2WCN_MTFTA': 0,
            'T2_LTFTA': 0,
            'LFTA': 0,
            '3WHA': 0,
            'HTHC': 0,
            'AH1B': 0,
            'T2_MTFTA': 0,
            'HA1': 0,
            'CN_LTB': 0,
            'HC2': 0,
            'ACNHTB': 0,
            '_2WCN_MTFTB': 0,
            'AH_HT1D': 0,
            '2WCN_LTFTA': 0,
            'ACNHT_GTB': 0,
            '2WCN_LTFTD': 0,
            '3WH2C': 0,
            'T1_MTFTD': 0,
            '3WHX': 0,
            'AH2A': 0,
            'MTFTB': 0,
            'HTHB2': 0,
            'CN_GTB': 0,
            'LTHTA': 0,
            'ACSC': 0,
            'AHC': 0,
            'EXG2_1': 0,
            'ACNHTC': 0,
            'ACSA': 0,
            'ACN_LTD': 0,
            '3WH_1HT2A': 0,
            'AH1D': 0,
            'HC1': 0,
            'HX': 0,
            'EXG1_8': 0,
            'CN_EXC': 0,
            'T1_MTFTA': 0,
            'CN_LTHT': 0,
            'ACND': 0,
            'HTHA': 0,
            'AHB': 0,
            'ACN_GTC': 0,
            'HTHCX': 0,
            '_2WCN_MTFTC': 0,
            'ACNHT_LTB': 0,
            'AH_HT1B': 0,
            'EXCN_HTB': 0,
            'AH2B': 0,
            'LTHTD': 0,
            'ACN_GTB': 0,
            'EXG2_4': 0,
            'HCX': 0,
            '2WCN_MTFTC': 0,
            'CN_GTC': 0,
            'AH_HT2D': 0,
            'CN_MTHTC': 0,
            'T1SBHY': 0,
            'T1SBHN': 0,
            'T2SBHY': 0,
            'T2SBHN': 0,
        },
        'additional_keys': [
            'HTH',
            'HTH{}1',
            'HTH{}X',
            'HTH{}2',
            'H',
            'H{}1',
            'H{}X',
            'H{}2',
            'LFT',
            'MTFT',
            'LTFT',
            'LHT',
            'MTHT',
            'LTHT',
            'CN',
            'CN_LT',
            'CN_GT',
            'CN_EX',
            'ACNHT',
            'ACNHT_LT',
            'ACNHT_GT',
            'ACSHT_',
            'ACN',
            'ACN_LT',
            'ACN_GT',
            'ACS',
            '3WH',
            '3WH1',
            '3WHX',
            '3WH2',
            '3WH_1HT',
            '3WH_1HT1',
            '3WH_1HTX',
            '3WH_1HT2',
            'LFT_T1',
            'T1_MTFT',
            'T1_LTFT',
            'T2_LFT',
            'T2_MTFT',
            'T2_LTFT',
            '_2WCN_FT',
            '2WCN_MTFT',
            '2WCN_LTFT',
            'CN_HT',
            'CN_MTHT',
            'CN_LTHT',
            'EXCN_HT',
            'AH',
            'AH1',
            'AH2',
            'AH_HT',
            'AH_HT1',
            'AH_HT2',
            '_2WCN_FT',
            '_2WCN_MTFT',
            '_2WCN_LTFT',
            'ACNHT',
            'ACNHT_LT',
            'ACNHT_GT',
            'ACSHT_',
            'LTFT_T1',
            'MTFT_T1',
            'LFT_T1',
            'LTFT_T2',
            'MTFT_T2',
            'LFT_T2'
        ],
        'vars': {
            'ous_ht_parsed': [],
            'ou_ht_key': None,
            'ous_fh_parsed': [],
            'ou_fh_key': None,
            'home_goals_parsed': [],
            'home_goals_key': None,
            'away_goals_parsed': [],
            'away_goals_key': None,
            'corners_fh_parsed': [],
            'corners_fh_key': None,
            'twowaycorners_ft_parsed': [],
            'twowaycorners_ft_key': None,
            'firsthcorners_ft_parsed': [],
            'firsthcorners_ft_key': None,
            'corners_a_fh_parsed': [],
            'corners_a_fh_key': None,
            'corners_a_ht_parsed': [],
            'corners_a_ht_key': None,
            'threewayhnd_ft_parsed': [],
            'threewayhnd_ft_key': None,
            'threewayhnd_1ht_parsed': [],
            'threewayhnd_1ht_key': None
        },
        'active_markets': {
            r'^Fulltime Result$',
            r'^Double Chance$',
            r'^Half Time Result$',
            r'^((\d{1,2})[a-z]{2}) Goal$',
            r'^Half Time/Full Time$',
            r'^Draw No Bet$',
            r'^Last Team to Score$',
            r'^Goals Odd/Even$',
            r'^Both Teams to Score$',
            r'^Both Teams to Score in 1st Half$',
            r'^Both Teams to Score in 2nd Half$',
            r'^To Win 2nd Half$',
            r'^Match Goals$',
            r'^reg_home_exact_goals$',
            r'^reg_away_exact_goals$',
            r'^reg_home_score_bothhalf$',
            r'^reg_away_score_bothhalf$',
            # r'^reg_home_score_1ht$',
            # r'^reg_away_score_1ht$',
            # r'^reg_home_score_2ht$',
            # r'^reg_away_score_2ht$',
            # r'^reg_home_clean_sheet$',
            # r'^reg_away_clean_sheet$',
            # r'^Game Won In Extra Time$',
            # r'^To Qualify$',
            # r'^((\d?){1,2}[a-z]{2}) Corner$',
            r'^First Half Goals$',
            r'^Alternative 1st Half Goals$',
            r'^reg_home_goals$',
            r'^reg_away_goals$',
            # r'^Total Corners$',
            # r'^Asian Corners$',
            # r'^1st Half Asian Corners$',
            # r'^2-Way Corners$',
            # r'^1st Half Corners$',
            r'^3-Way Handicap$',
            r'^Alternative 3-Way Handicap$',
            # r'^1st Half 3-Way Handicap$',
            # r'^Alternative 1st Half 3-Way Handicap$',
            r'^Result / Both Teams To Score$',
            # r'^Method of Victory$', # ne radi
            r'^Alternative Match Goals$',
            r'^Final Score$',
            r'^Half Time Correct Score$',
        },
        'quota_multiplier': {
            'full time result': 1.02,
            'double chance': 1.02,
            'half time result': 1.02,
            'next goal': 1.02,
            'half time/full time': 1.02,
            'draw no bet': 1.02,
            'last team to score': 1.02,
            'goals odd/even': 1.02,
            'both team to score': 1.02,
            'full time result in 1st half': 1.02,
            'full time result in 2nd half': 1.02,
            'to win 2nd half': 1.02,
            'match goals': 1.02,
            'home exact goals': 1.02,
            'away exact goals': 1.02,
            'home score bothhalf': 1.02,
            'away score bothhalf': 1.02,
            'home goals': 1.02,
            'away goals': 1.02,
            '3-way handicap': 1.02,
            'result / both teams to score': 1.02,
            'first half goals': 1.02,
            'alternative 1st half goals': 1.02,
            'alternative match goals': 1.02,
        }
    },
    '6': {  #Tennis
        'initial_odds': {
            'TF1': 0,
            'TF2': 0,
            'HC_GIM_MD2': 0,
            'S3_1': 0,
            'TCS2': 0,
            'HC_GIM_MD1': 0,
            'TCS1': 0,
            'S3_2': 0,
            'LGIM_MD_INFO': 0,
            'LGIM_MD_P': 0,
            'LGIM_MD_M': 0,
            'HC_GIM_MD_INFO': 0,
            'LST': 0,
            'LTST': 0,
            'MTST': 0,
            'LGIS_MD_INFO': 0,
            'LGIS_MD_P': 0,
            'LGIS_MD_M': 0,
            'LGIS_MD_INFO1': 0,
            'LGIS_MD_P1': 0,
            'LGIS_MD_M1': 0,
            'LGIS_MD_INFO2': 0,
            'LGIS_MD_P2': 0,
            'LGIS_MD_M2': 0,
            'LGIS_MD_INFO3': 0,
            'LGIS_MD_P3': 0,
            'LGIS_MD_M3': 0,
            'LGIS_MD_INFO4': 0,
            'LGIS_MD_P4': 0,
            'LGIS_MD_M4': 0,
            'LGIS_MD_INFO5': 0,
            'LGIS_MD_P5': 0,
            'LGIS_MD_M5': 0,
            'TS2': 0,
            'TS3': 0,
            'TS4': 0,
            'TS5': 0,
            'CGW1': 0,
            'CGW2': 0,
            'NGW1': 0,
            'NGW2': 0,
            'T1GW': 0,
            'LTT1GW': 0,
            'MTT1GW': 0,
            'T2GW': 0,
            'LTT2GW': 0,
            'MTT2GW': 0,
            'HA': 0,
            'HA1': 0,
            'HA2': 0,
            'HAX': 0,
            'PTSH':0,
            'PTSH1':0,
            'PTSH2':0,
            'PTSHX':0,
        },
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': [
            'HTH',
            'HTH{}1',
            'HTH{}X',
            'HTH{}2'
        ],
        'vars': {
            'ous_s1_parsed': [],
            'ou_s1_key': None,
            'ous_s2_parsed': [],
            'ou_s2_key': None,
            'ous_s3_parsed': [],
            'ou_s3_key': None,
            'ous_s4_parsed': [],
            'ou_s4_key': None,
            'tgim_parsed': [],
            'tgim_key': None,
            't1gw_parsed': [],
            't1gw_key': None,
            't2gw_parsed': [],
            't2gw_key': None,
            'hendbet_parsed': [],
            'hendbet_key': None,
            'hendbet3w_parsed': [],
            'hendbet3w_key': None,
            'tgs_1_parsed': [],
            'tgs_1_key': None,
            'tgs_2_parsed': [],
            'tgs_2_key': None,
            'tgs_3_parsed': [],
            'tgs_3_key': None,
            'tgs_4_parsed': [],
            'tgs_4_key': None,
            'tgs_5_parsed': [],
            'tgs_5_key': None,
            'ss_1_parsed': [],
            'ss_1_key': None,
            'ss_2_parsed': [],
            'ss_2_key': None,
            'ss_3_parsed': [],
            'ss_3_key': None,
            'ss_4_parsed': [],
            'ss_4_key': None,
            'ss_5_parsed': [],
            'ss_5_key': None,
        },
        'active_markets': {
            r'^Match Winner',
            r'^Set [1-5]{1} Winner',
            # r'^Total Sets$',
            r'^Total Games in Match',
            # r'^Handicap Betting 3-Way',
            # r'^[0-9]{1,2}[a-z]{2} Game Winner',
            # r'^[0-9]{1,2}[a-z]{2} Game to Deuce',
            # r'^Set Betting',
            # r'^Match Tie-Break Total Points',
            # r'^Set [0-9]{1} Tie Break - Total Points'
            # r'^Match Tie-Break Winner',
            # r'^Set [0-9]{1} Tie Break Winner',
            # r'^1st Point Winner [0-9]{1,2}[a-z]{2} Game',
            # r'^Total Games$',
            # r'^Handicap Betting$',
            # r'^team1_games_won$',
            # r'^team2_games_won',
            # r'^Set [1-5]{1} Score',
            # r'^Total Games in Set [1-5]{1}',
        },
        'quota_multiplier': {
            'match winner': 1.02,
            'set winner': 1.02,
            'total sets': 1.02,
            'total games in match': 1.02,
            'curent and next game winner': 1.02,
            'team1 games won': 1.02,
            'team2 games won': 1.02,
            'handicap betting': 1.02,
            'Total games in set': 1.02
        }
    },
    '2': { #basketball
        'initial_odds': {
            'F1': 0,
            'FX': 0,
            'F2': 0,
            'SHT1': 0,
            'SHTX': 0,
            'SHT2': 0,
            'LFT': 0,
            'LTFT': 0,
            'MTFT': 0,
            'FHT1': 0,
            'FHT2':0,
            'FHTX':0,
            'LT1': 0,
            'LTT1': 0,
            'ET1': 0,
            'MTT1': 0,
            'LT2': 0,
            'LTT2': 0,
            'ET2': 0,
            'MTT2': 0,
            'LQ2TR': 0,
            'LTQ2TR': 0,
            'MTQ2TR': 0,
            'LQ3TR': 0,
            'LTQ3TR': 0,
            'MTQ3TR': 0,
            'LQ4TR': 0,
            'LTQ4TR': 0,
            'MTQ4TR': 0,
            'LSHT': 0,
            'LTLSHT': 0,
            'MTLSHT': 0,
            'LHT': 0,
            'LTHT': 0,
            'MTHT': 0,
            'FQ2TRH': 0,
            'FQ2TRH1': 0,
            'FQ2TRH2': 0,
            'FQ3TRH': 0,
            'FQ3TRH1': 0,
            'FQ3TRH2': 0,
            'FQ4TRH': 0,
            'FQ4TRH1': 0,
            'FQ4TRH2': 0,
            'HTHA': 0,
            'HTHA1': 0,
            'HTHA2': 0,
            'SHTHA': 0,
            'SHTHA1': 0,
            'SHTHA2': 0,
            'SHTA': 0,
            'SHTA1': 0,
            'SHTA2': 0,
            'FQTR1': 0,
            'FQTRX': 0,
            'FQTR2': 0,
            'FQ2TR1': 0,
            'FQ2TRX': 0,
            'FQ2TR2': 0,
            'FQ3TR1': 0,
            'FQ3TRX': 0,
            'FQ3TR2': 0,
            'FQ4TR1': 0,
            'FQ4TRX': 0,
            'FQ4TR2': 0,
            'FQTRH': 0,
            'FQTRH1': 0,
            'FQTRH2': 0,
            'LQTR': 0,
            'LTQTR': 0,
            'MTQTR': 0,
            'ODD': 0,
            'EVEN': 0,
        },
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': [
            'HTH',
            'HTH{}1',
            'HTH{}X',
            'HTH{}2',
            'H',
            'H{}1',
            'H{}2',
        ],
        'vars': {
            'hth_parsed': [],
            'hth_key': None,
            'htsh_parsed': [],
            'htsh_key': None,
            '1qh_parsed': [],
            '1qh_key': None,
            '2qh_parsed': [],
            '2qh_key': None,
            '3qh_parsed': [],
            '3qh_key': None,
            '4qh_parsed': [],
            '4qh_key': None,

            'h2w_parsed': [],
            'h2w_key': None,

            '1qt2w_parsed': [],
            '1qt2w_key': None,
            '2qt2w_parsed': [],
            '2qt2w_key': None,
            '3qt2w_parsed': [],
            '3qt2w_key': None,
            '4qt2w_parsed': [],
            '4qt2w_key': None,
            'htt2w_parsed': [],
            'htt2w_key': None,
            'shtt2w_parsed': [],
            'shtt2w_key': None,
            't2w_parsed': [],
            't2w_key': None,

            'htt3t_parsed': [],
            'htt3w_key': None,
            'shtt3t_parsed': [],
            'shtt3w_key': None,
            't3t_parsed': [],
            't3w_key': None,
            'q1t3t_parsed': [],
            'q1t3w_key': None,
            'q2t3t_parsed': [],
            'q2t3w_key': None,
            'q3t3t_parsed': [],
            'q3t3w_key': None,
            'q3t4t_parsed': [],
            'q3t4w_key': None,

            '1qtt_parsed': [],
            '1qtt_key': None,
            '2qtt_parsed': [],
            '2qtt_key': None,
            '3qtt_parsed': [],
            '3qtt_key': None,
            '4qtt_parsed': [],
            '4qtt_key': None,
            'httt_parsed': [],
            'httt_key': None,
            'shttt_parsed': [],
            'shttt_key': None,
            'tt_parsed': [],
            'tt_key': None,

            '1qmov_parsed': [],
            '1qmov_key': None,
            '2qmov_parsed': [],
            '2qmov_key': None,
            '3qmov_parsed': [],
            '3qmov_key': None,
            '4qmov_parsed': [],
            '4qmov_key': None,
            'htmov_parsed': [],
            'htmov_key': None,
            'shtmov_parsed': [],
            'shtmov_key': None,
            'wm3w_parsed': [],
            'wm3w_key': None,
        },
        'active_markets': {
            r'^To Win Match',
            # r'^1st Half - Winner \(2-way\)'
            # r'^2nd Half - Winner \(2-way\)',
            # r'^1st Quarter - Winner \(2-way\)',
            # r'^2nd Quarter - Winner \(2-way\)',
            # r'^3rd Quarter - Winner \(2-way\)',
            # r'^4th Quarter - Winner \(2-way\)',
            r'^Handicap 2-Way',
            # r'^1st Quarter - Handicap',
            # r'^2nd Quarter - Handicap',
            # r'^3rd Quarter - Handicap',
            # r'^4th Quarter - Handicap',
            # r'^1st Half - Handicap',
            # r'^2nd Half - Handicap',
            # r'Double Result',
            # r'Will There Be Overtime?',
            # r'^1st Quarter - Total Odd/Even',
            # r'^2nd Quarter - Total Odd/Even',
            # r'^3rd Quarter - Total Odd/Even',
            # r'^4th Quarter - Total Odd/Even',
            # r'^1st Half - Total Odd/Even',
            # r'^1st Half Total Odd/Even ',
            # r'^2nd Half - Total Odd/Even',
            # r'^2nd Half Total Odd/Even ',
            # r'^Game Total Odd/Even',
            # r'^1st Quarter - Total\(2-way\)',
            # r'^2nd Quarter - Total\(2-way\)',
            # r'^3rd Quarter - Total\(2-way\)',
            # r'^4th Quarter - Total\(2-way\)',
            # r'^1st Half - Total \(2-way\)',
            # r'^2nd Half - Total \(2-way\)',
            r'^Total 2-Way',
            r'^1st Half - Winner \(3-Way\)',
            # r'^2nd Half - Winner \(3-way\)',
            # r'^Winner 3-Way',
            # r'^1st Quarter - Winner \(3-way\)',
            # r'^2nd Quarter - Winner \(3-way\)',
            # r'^3rd Quarter - Winner \(3-way\)',
            # r'^4th Quarter - Winner \(3-way\)',
            # r'^1st Half - Total \(3-way\)',
            # r'^2nd Half - Total \(3-way\)',
            # r'^Total 3-Way',
            # r'^1st Quarter - Total \(3-way\)',
            # r'^2nd Quarter - Total \(3-way\)',
            # r'^3rd Quarter - Total \(3-way\)',
            # r'^4th Quarter - Total \(3-way\)',
            # r'^1st Quarter - Team Totals',
            # r'^2nd Quarter - Team Totals',
            # r'^3rd Quarter - Team Totals',
            # r'^4th Quarter - Team Totals',
            # r'^1st Half - Team Totals',
            # r'^2nd Half - Team Totals',
            # r'^Team Totals',
            # r'^1st Quarter Margin of Victory',
            # r'^2nd Quarter Margin of Victory',
            # r'^3rd Quarter Margin of Victory',
            # r'^4th Quarter Margin of Victory',
            # r'^1st Half - Margin of Victory',
            # r'^2nd Half - Margin of Victory',
            # r'^Winning Margin 3-Way',
        },
        'quota_multiplier': {
            'to win match': 1.02,
            '1st half - winner 3-way': 1.02,
            '2nd half - winner 3-way': 1.02,
            '1st quarter - winner 3-way': 1.02,
            '2nd quarter - winner 3-way': 1.02,
            '3rd quarter - winner 3-way': 1.02,
            '4th quarter - winner 3-way': 1.02,
            'handicap 2-way': 1.02,
            'total 2-way': 1.02,
            'game total odd/even': 1.02,
            '1st quarter - handicap': 1.02,
            '2nd quarter - handicap': 1.02,
            '3rd quarter - handicap': 1.02,
            '4th quarter - handicap': 1.02,
            '1st half - handicap': 1.02,
            '2nd half - handicap': 1.02,
            '1st quarter - total 2-way': 1.02,
            '2nd quarter - total 2-way': 1.02,
            '3rd quarter - total 2-way': 1.02,
            '4th quarter - total 2-way': 1.02,
            '1st half - total 2-way': 1.02,
            '2nd half - total 2-way': 1.02,
            'team totals': 1.02
        }
    },
    '5': { #Voleyball
        'initial_odds': {
            'TF1': 0,
            'TFX': 0,
            'TF2': 0,
            'HA': 0,
            'HA1': 0,
            'HA2': 0,
            'LFT': 0,
            'LTFT': 0,
            'MTFT': 0,
            'LT1':0,
            'LTT1':0,
            'MTT1':0,
            'LT2':0,
            'LTT2':0,
            'MTT2':0,
            'HAX': 0,
            'LPIS_MD_INFO': 0,
            'LPIS_MD_P': 0,
            'LPIS_MD_M': 0,
        },
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': [
            'HTH',
            'HTH{}1',
            'HTH{}X',
            'HTH{}2',
        ],
        'vars': {
            'hth_parsed': [],
            'hth_key': None,
            'htsh_parsed': [],
            'htsh_key': None,
            '1qh_parsed': [],
            '1qh_key': None,
            '2qh_parsed': [],
            '2qh_key': None,
            '3qh_parsed': [],
            '3qh_key': None,
            '4qh_parsed': [],
            '4qh_key': None,

        },
        'active_markets': {
            r'^Match Winner',
            # r'^Set [1-5]{1} Winner',
            r'^reg_home_total$',
            r'^reg_away_total$',
            # r'^Set [1-5]{1} Total',
            r'^Match Handicap \(Sets\)',
            # r'^Set [1-5]{1} Handicap$',
            # r'^Set [1-5]{1} Odd/Even',
            # r'^Match Total Odd/Even ',
            # r'^Set [1-5]{1} Extra Points',
        },
        'quota_multiplier': {
            'match winner': 1.02,
            'home total': 1.02,
            'away total': 1.02,
            'current set': 1.02,
            'match total': 1.02,
            'match handicap sets': 1.02
        }
    },
    '3': { #Handball
        'initial_odds': {'F1': 0, 'FX': 0, 'F2': 0, 'HA': 0, 'HA1': 0, 'HA2': 0,'LFT': 0, 'LTFT': 0, 'MTFT': 0, 'NG1':0, 'NGX':0, 'NG2':0, 'DC1X':0, 'DC12':0, 'DCX2':0, 'W1':0, 'W2':0, 'LT1':0, 'LTT1':0, 'MTT1':0, 'LT2':0, 'MTT2':0, 'LTT2':0,},
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': ["HTH", "HTH{}1", "HTH{}X", "HTH{}2"],
        'vars': {
            't2w_parsed': [],
            't2w_key': None,
            'h2w_parsed': [],
            'h2w_key': None,
            'hth2w_parsed': [],
            'hth2w_key': None,
            'shth2w_parsed': [],
            'shth2w_key': None,
            'threewayhnd_parsed': [],
            'threewayhnd_key': None,
            'threewayhnd_ht_parsed': [],
            'threewayhnd_ht_key': None,
            'threewayhnd_sht_parsed': [],
            'threewayhnd_sht_key': None,
        },
        'active_markets': {
            r'^Full Time Result',
            # r'^2nd Half First Goal',
            # r'^1st Half Result 3-Way',
            # r'^2nd Half Result 3-Way',
            # r'Double Chance',
            # r'1st Half Double Chance',
            # r'2nd Half Double Chance',
            # r'Draw No Bet',
            # r'1st Half Draw No Bet',
            # r'2nd Half Draw No Bet',
            # r'Double Result',
            # r'^Home Total Odd/Even',
            # r'^Away Total Odd/Even',
            # r'^1st Half Total Odd or Even',
            # r'^2nd Half Total Odd or Even',
            # r'^Home Game Total',
            # r'^1st Half Home Total',
            # r'^2nd Half Home Total',
            # r'^Away Game Total',
            # r'^1st Half Away Total',
            # r'^2nd Half Away Total',
            r'^Total 2-Way',
            # r'^Alternative Total 2-Way',
            # r'^1st Half Total 2-Way',
            # r'^2nd Half Total 2-Way',
            r'^((\d{1,2})[a-z]{2}) Goal',
            r'^Handicap 2-Way',
            # r'^Alternative Handicap 2-Way',
            # r'^1st Half Handicap 2-Way',
            # r'^2nd Half Handicap 2-Way ',
            # r'^Handicap 3-Way',
            # r'^Alternative Handicap 3-Way',
            # r'^1st Half Handicap 3-Way',
            # r'^2nd Half Handicap 3-Way',
        },
        'quota_multiplier': {
            'full time result': 1.02,
            'double chance': 1.02,
            'next goal': 1.02,
            'draw no bet': 1.02,
            'home game total': 1.02,
            'away goal total': 1.02,
            'total 2-way': 1.02,
            'handicap 2-way': 1.02,
        }
    },
    '4': { #Ice Hockey
        'initial_odds': {'LFT': 0,
                         'LTFT': 0,
                         'MTFT': 0,
                         'F1': 0,
                         'FX': 0,
                         'F2': 0,
                         'HA': 0,
                         'HA1': 0,
                         'HA2': 0,
                         'NG1': 0,
                         'GG': 0,
                         'NG': 0,
                         'ODD': 0,
                         'EVEN': 0,
                         'NGX':0,
                         'NG2':0,
                         'DC1X':0,
                         'DC12':0,
                         'DCX2':0,
                         'W1':0,
                         'W2':0,
                         'LT1': 0,
                         'LTT1': 0,
                         'MTT1': 0,
                         'LT2': 0,
                         'LTT2': 0,
                         'MTT2': 0,
                         'LTP1TR': 0,
                         'MTP1TR': 0,
                         'LTP2TR': 0,
                         'MTP2TR': 0,
                         'LTP3TR': 0,
                         'MTP3TR': 0,
                         'FTR1': 0,
                         'FTRX': 0,
                         'FTR2': 0,
                         'FTP2R1': 0,
                         'FTP2RX': 0,
                         'FTP2R2': 0,
                         'FTP3R1': 0,
                         'FTP3RX': 0,
                         'FTP3R2': 0,
                         },
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': ["LFT{}", "MTFT{}", "LTFT{}", "HTH", "HTH{}1", "HTH{}X", "HTH{}2"],
        'vars': {
            'pl_parsed': [],
            'pl_key': None,
            'p1pl_parsed': [],
            'p1pl_key': None,
            'p2pl_parsed': [],
            'p2pl_key': None,
            'p3pl_parsed': [],
            'p3pl_key': None,

            'gt_parsed': [],
            'gt_key': None,
            'p1gt_parsed': [],
            'p1gt_key': None,
            'p2gt_parsed': [],
            'p2gt_key': None,
            'p3gt_parsed': [],
            'p3gt_key': None,

            'ht_parsed': [],
            'ht_key': None,
            'p1ht_parsed': [],
            'p1ht_key': None,
            'p2ht_parsed': [],
            'p2ht_key': None,
            'p3ht_parsed': [],
            'p3ht_key': None,

            'at_parsed': [],
            'at_key': None,
            'p1at_parsed': [],
            'p1at_key': None,
            'p2at_parsed': [],
            'p2at_key': None,
            'p3at_parsed': [],
            'p3at_key': None,

            'hgt3w_parsed': [],
            'hgt3w_key': None,
            'agt3w_parsed': [],
            'agt3w_key': None,

            'p1gt3w_parsed': [],
            'p1gt3w_key': None,
            'p2gt3w_parsed': [],
            'p2gt3w_key': None,
            'p3gt3w_parsed': [],
            'p3gt3w_key': None,
        },
        'active_markets': {
            # r'^Both Teams to Score At Least 2 Goals',
            # r'^Both Teams to Score At Least 3 Goals',
            # r'^Will Match go to Overtime',
            # r'^When Will Game End',
            # r'^Highest Scoring Period',
            # r'^Team To Score Last In Regulation',
            # r'^Money Line 3-way',
            # r'^Team To Win The Most Periods',
            # r'^Winner 3-Way',
            # r'^Period 1 Winner 3-Way',
            # r'^Period 2 Winner 3-Way',
            # r'^Period 3 Winner 3-Way',
            # r'^Total Odd/Even',
            # r'^Period 1 Total Odd/Even',
            # r'^Period 2 Total Odd/Even',
            # r'^Period 3 Total Odd/Even',
            r'Double Chance',
            # r'Period 1 Double Chance',
            # r'Period 2 Double Chance',
            # r'Period 3 Double Chance',
            r'^Draw No Bet$',
            r'^((\d{1,2})[a-z]{2}) Goal',
            # r'^Puck Line',
            # r'^Period 1 Puck Line',
            # r'^Period 2 Puck Line',
            # r'^Period 3 Puck Line',
            r'^Game Total$',
            # r'^Period 1 Game Total',
            # r'^Period 2 Game Total',
            # r'^Period 3 Game Total',
            # r'^reg_home_home_total$',
            # r'^reg_home_p1_home_total$',
            # r'^reg_home_p2_home_total$',
            # r'^reg_home_p3_home_total$',
            # r'^reg_away_away_total$',
            # r'^reg_away_p1_away_total$',
            # r'^reg_away_p2_away_total$',
            # r'^reg_away_p3_away_total$',
            # r'^reg_home_gt3w$',
            # r'^reg_away_gt3w$',
            # r'^Period 1 Game Total 3-Way',
            # r'^Period 3 Game Total 3-Way',
            # r'^Period 3 Game Total 3-Way',
        },
        'quota_multiplier': {
            'money line 3-way': 1.02,
            'period 1 winner 3-way': 1.02,
            'period 2 winner 3-way': 1.02,
            'period 3 winner 3-way': 1.02,
            'double chance': 1.02,
            'draw no bet': 1.02,
            'next goal': 1.02,
            'game total': 0.97,
            'period 1 game total': 1.02,
            'period 2 game total': 1.02,
            'period 3 game total': 1.02,
            'home game total': 1.02,
            'away game total': 1.02,
        }
    },
    '8': { #NFL
        'initial_odds': {'LFT': 0,
                         'LTFT': 0,
                         'MTFT': 0,
                         'F1': 0,
                         'FX': 0,
                         'F2': 0,
                         'HA': 0,
                         'HA1': 0,
                         'HA2': 0,
                         'NG1': 0,
                         'NGX':0,
                         'NG2':0,
                         'DC1X':0,
                         'DC12':0,
                         'DCX2':0,
                         'W1':0,
                         'W2':0,
                         },
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': ["LFT{}", "MTFT{}", "LTFT{}", "HTH", "HTH{}1", "HTH{}X", "HTH{}2"],
        'vars': {
            'h2w_parsed': [],
            'h2w_key': None,
            'h1t2w_parsed': [],
            'h1t2w_key': None,
            'h2t2w_parsed': [],
            'h2t2w_key': None,
            't2w_parsed': [],
            't2w_key': None,
            't3w_parsed': [],
            't3w_key': None,
            'htp2w_parsed': [],
            'htp2w_key': None,
            'atp2w_parsed': [],
            'atp2w_key': None,
            'htp3w_parsed': [],
            'htp3w_key': None,
            'atp3w_parsed': [],
            'atp3w_key': None
        },
        'active_markets': {
            r'^match winner 2-way',
            # r'^1st half winner 2-way',
            # r'^2nd half winner 2-way',
        },
        'quota_multiplier': {
            'match winner 2-way': 1.02,
            '1st half winner 2-way': 1.02,
            '2nd half winner 2-way': 1.02,
            'quarter winner 2-way': 1.02,
            'quarter winner 3-way': 1.02,
            'will game go to overtime': 1.02,
            'highest scoring half': 1.02,
            'quarter handicap 2-way': 1.02,
            'half handicap 2-way': 1.02,
            'handicap 2-way': 1.02,
            'handicap 3-way': 1.02,
            '1st half total 2-way': 1.02,
            '2nd half total 2-way': 1.02,
            'total 2-way': 1.02,
            'home_tp2w': 1.02,
            'away_tp2w': 1.02,
            'home_tp3w': 1.02,
            'away_tp3w': 1.02,
        }
    },
    '7': { #waterpolo
        'initial_odds': {
            'F1': 0,
            'FX': 0,
            'F2': 0,
            'LFT': 0,
            'LTFT': 0,
            'MTFT': 0,
            'FHT1': 0,
            'FHT2':0,
            'FHTX':0,
        },
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': [
            'HTH',
            'HTH{}1',
            'HTH{}X',
            'HTH{}2',
            'H',
            'H{}1',
            'H{}2',
        ],
        'vars': {
            'h2w_parsed': [],
            'h2w_key': None,
            'hth2w_parsed': [],
            'hth2w_key': None,
            'shth2w_parsed': [],
            'shth2w_key': None,
            '1qh2w_parsed': [],
            '1qh2w_key': None,
            '2qh2w_parsed': [],
            '2qh2w_key': None,
            '3qh2w_parsed': [],
            '3qh2w_key': None,
            '4qh2w_parsed': [],
            '4qh2w_key': None,

            'h3w_parsed': [],
            'h3w_key': None,
            'hth3w_parsed': [],
            'hth3w_key': None,
            'shth3w_parsed': [],
            'shth3w_key': None,
            '1qh3w_parsed': [],
            '1qh3w_key': None,
            '2qh3w_parsed': [],
            '2qh3w_key': None,
            '3qh3w_parsed': [],
            '3qh3w_key': None,
            '4qh3w_parsed': [],
            '4qh3w_key': None,

        },
        'active_markets': {
            r'^To Win Match',
        },
        'quota_multiplier': {
            'full time result': 1.02,
            'double chance': 1.02,
            'draw no bet': 1.02,
            'double result': 1.02,
            'next goal': 1.02,
            '1st half winner 2-way': 1.02,
            '2nd half winner 2-way': 1.02,
            'current quarter winner 2-way': 1.02,
            '1st half winner 3-way': 1.02,
            '2nd half winner 3-way': 1.02,
            'current quarter winner 3-way': 1.02,
            'total goals odd/even': 1.02,
            'home goals odd/even': 1.02,
            'away goals odd/even': 1.02,
            'half away goals odd-even': 1.02,
            'half home goals odd-even': 1.02,
            'half total goals odd-even': 1.02,
            'quarter total goals odd-even': 1.02,
            'quarter home goals odd-even': 1.02,
            'quarter away goals odd-even': 1.02,
            'home total goals': 1.02,
            'away total goals': 1.02,
            '1st half total goals': 1.02,
            '2nd half total goals': 1.02,
            '1st half home total goals': 1.02,
            '2nd half home total goals': 1.02,
            '1st half away total goals': 1.02,
            '2nd half away total goals': 1.02,
            'quarter total goals': 1.02,
            'quarter home total goals': 1.02,
            'quarter away total goals': 1.02,
            'handicap 2-way': 1.02,
            '1st half handicap 2-way': 1.02,
            '2nd half handicap 2-way': 1.02,
            'quarter handicap 2-way': 1.02,
            'handicap 3-way': 1.02,
            '1st half handicap 3-way': 1.02,
            '2nd half handicap 3-way': 1.02,
            'quarter handicap 3-way': 1.02,
        }
    },
    '9': { #Baseball
        'initial_odds': {'F1': 0, 'FX': 0, 'F2': 0, 'HA': 0, 'HA1': 0, 'HA2': 0,'LFT': 0, 'LTFT': 0, 'MTFT': 0,},
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': ["HTH", "HTH{}1", "HTH{}X", "HTH{}2"],
        'vars': {
            'rl_parsed': [],
            'rl_key': None,
            'irl_parsed': [],
            'irl_key': None,
        },
        'active_markets': {}
    },
    '17': { #Cricket
        'initial_odds': {'F1': 0, 'FX': 0, 'F2': 0, 'HA': 0, 'HA1': 0, 'HA2': 0,'LFT': 0, 'LTFT': 0, 'MTFT': 0,},
        # ne moze 1 da se upisuje u uglaste zagrade, zato sto ne preskace prvi element, nego mu dodeljuje jedinicu
        'additional_keys': ["HTH", "HTH{}1", "HTH{}X", "HTH{}2"],
        'vars': {
            'rl_parsed': [],
            'rl_key': None,


            'h2w_parsed': [],
            'h2w_key': None,
            'hth2w_parsed': [],
            'hth2w_key': None,
            'shth2w_parsed': [],
            'shth2w_key': None,
            'threewayhnd_parsed': [],
            'threewayhnd_key': None,
            'threewayhnd_ht_parsed': [],
            'threewayhnd_ht_key': None,
            'threewayhnd_sht_parsed': [],
            'threewayhnd_sht_key': None,
        },
        'active_markets': {}
    },
}
