#Nasa numeracija sportova
sports = {
    'Football': 1,
    'Basketball': 2,
    'Handball': 3,
    'Hockey': 4,
    'Volleyball': 5,
    'Tennis': 6,
    'Waterpolo': 7,
    'NFL': 8,
    'Special': 9,
    'Baseball': 10,
    'Fantasy': 11,
    'Futsal': 12,
    'Beach Volleyball': 13,
    'Table Tennis': 14,
    'Golf': 15,
    'Horse Racing': 16,
    'Cricket': 17,
    'Darts': 18,
    'E Sports': 19,
    'Greyhounds': 20,
    'RugbyUnion': 21,
    'RugbyLeague': 22,
    'Speedway': 23
}

#TIP BET numeracija sportova
tip_bet_sports_nmb = {
    'Football': 1,
    'Tennis': 13,
    'Baseball': 16,
    'Basketball': 18,
    'E Sports': 151,
    'Cricket': 3,
    'Handball': 78,
    'Golf': 7,
    'NFL': 12,
    'Hockey': 17,
    'Volleyball': 91,
    'Horse Racing': 2,
    'Rugby League': 19,
    'RugbyUnion': 8,
    'Waterpolo': 110,
    'Beach Volleyball': 95,
    'Greyhounds': 4,

    #nisu provereni
    'Special': 8,
    'Fantasy': 10,
    'Futsal': 11,
    'Table Tennis': 14,
    'Darts': 18,
    'Speedway': 22
}

rev = {sports[sport]: sport for sport in sports}

# normalized sports
normalized_sport = {
    'Soccer': 'Football',
    'Football': 'Football',
    'Fudbal': 'Football',
    'soccer': 'Football',
    'football': 'Football',
    'euro 2016': 'Football',
    'wc 2018': 'Football',
    'Ice Hockey': 'Hockey',
    'Hokej na ledu': 'Hockey',
    'ice hockey': 'Hockey',
    'Ice-Hockey': 'Hockey',
    'ice-hockey': 'Hockey',
    'Ice-hockey': 'Hockey',
    'Hockey': 'Hockey',
    'Basketball': 'Basketball',
    'basketball': 'Basketball',
    'Tenis': 'Tennis',
    'Tennis': 'Tennis',
    'tennis': 'Tennis',
    'Odbojka': 'Volleyball',
    'Volleyball': 'Volleyball',
    'volleyball': 'Volleyball',
    'Handball': 'Handball',
    'Rukomet': 'Handball',
    'handball': 'Handball',
    'Beach Volleyball': 'Beach Volleyball',
    'Table Tennis': 'Table Tennis',
    'Baseball': 'Baseball',
    'Golf': 'Golf',
    'NFL': 'NFL',
    'American Football': 'NFL',
    'American-Football': 'NFL',
    'American football': 'NFL',
    'American-football': 'NFL',
    'american football': 'NFL',
    'american-football': 'NFL',
    'Water Polo': 'Waterpolo',
    'WaterPolo': 'Waterpolo',
    'Water polo': 'Waterpolo',
    'Water-polo': 'Waterpolo',
    'Water-Polo': 'Waterpolo',
    'Waterpolo': 'Waterpolo',
    'Horse Racing': 'Horse Racing',
    'Futsal': 'Futsal',
    'Cricket': 'Cricket',
    'E-Sports': 'E-Sports',
    'Greyhounds': 'Greyhounds',
    'Rugby': 'Rugby',
    'Rugby League': 'Rugby League',
    'Rugby Union': 'RugbyUnion',
    'RugbyUnion': 'RugbyUnion',
    'Speedway': 'Speedway',
    'Badminton': 'Badminton',
    'Darts': 'Darts',
    'Alpine Skiing': 'Alpine Skiing',
    'Bowls': 'Bowls',
    'Snooker': 'Snooker',
    'Biathlon': 'Biathlon',
    'Australian Rules': 'Australian Rules',
    'Supercars': 'Supercars',
    'Pool': 'Pool',
    'Squash': 'Squash',
    'Cycling': 'Cycling',
    'Cross Country Skiing': 'Cross Country Skiing',
}
